package app;

public  enum TiposMensaje {
    IDENTIFY, STATUS, NEW_STATUS, USERS, MESSAGE, PUBLIC_MESSAGE, CREATE_ROOM, INVITE, 
    JOIN_ROOM, ROOM_USERS, ROOM_MESSAGE, LEAVE_ROOM, DISCONNECT, NEW_USER, USER_LIST, MESSAGE_FROM,
    PUBLIC_MESSAGE_FROM, INVITE_FROM, JOINED_FROM, ROOM_USER_LIST, ROOM_MESSAGE_FROM,
    LEFT_ROOM,  DISCONNECTED, NEW_ROOM, INVITATION, JOINED_ROOM, 
    
    ERROR, WARNING,  INFO, INVALID;
    
}
